# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime
import os
from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import cv2 as cv
from PyQt5.QtGui import QImage, QPixmap

from face_recog import face_recog
import DatabaseConnection as dbClass

CapimageStorLoc = "CapturedImage"

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 562)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)

        self.logic = 0
        self.value = 1
        self.RollNumer = 0
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        font = QtGui.QFont()
        font.setPointSize(16)
        self.CameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.CameraButton.setGeometry(QtCore.QRect(170, 17, 431, 41))
        self.CameraButton.setObjectName("CameraButton")
        self.CameraButton.setFont(font)
        self.CameraButton.clicked.connect(self.onClicked)
        self.Photo_Box = QtWidgets.QLabel(self.centralwidget)
        self.Photo_Box.setGeometry(QtCore.QRect(20, 90, 321, 311))
        self.Photo_Box.setText("")
        self.Photo_Box.setPixmap(QtGui.QPixmap("ImageBasic/Train/Firoz Rangrez/0_2.jpg"))
        #self.Photo_Box.setScaledContents(True)
        self.Photo_Box.setObjectName("Photo_Box")

        self.Photo_Box.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.RollNumber_Label = QtWidgets.QLabel(self.centralwidget)
        self.RollNumber_Label.setGeometry(QtCore.QRect(390, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.RollNumber_Label.setFont(font)
        self.RollNumber_Label.setScaledContents(True)
        self.RollNumber_Label.setObjectName("RollNumber_Label")
        self.CurrentYear_Label = QtWidgets.QLabel(self.centralwidget)
        self.CurrentYear_Label.setGeometry(QtCore.QRect(390, 280, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.CurrentYear_Label.setFont(font)
        self.CurrentYear_Label.setScaledContents(True)
        self.CurrentYear_Label.setObjectName("CurrentYear_Label")

        self.Image_AdmissionYear = QtWidgets.QTextEdit(self.centralwidget)
        self.Image_AdmissionYear.setGeometry(QtCore.QRect(890, 270, 211, 31))
        self.Image_AdmissionYear.setObjectName("Image_AdmissionYear")
        self.Attendance_ConfirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.Attendance_ConfirmButton.setGeometry(QtCore.QRect(260, 490, 181, 28))
        self.Attendance_ConfirmButton.setObjectName("Attendance_ConfirmButton")
        self.RollNumber_LabelVal = QtWidgets.QLabel(self.centralwidget)
        self.RollNumber_LabelVal.setGeometry(QtCore.QRect(540, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RollNumber_LabelVal.setFont(font)
        self.RollNumber_LabelVal.setText("")
        self.RollNumber_LabelVal.setObjectName("RollNumber_LabelVal")
        self.CurrentYear_LabelVal = QtWidgets.QLabel(self.centralwidget)
        self.CurrentYear_LabelVal.setGeometry(QtCore.QRect(550, 280, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CurrentYear_LabelVal.setFont(font)
        self.CurrentYear_LabelVal.setText("")
        self.CurrentYear_LabelVal.setObjectName("CurrentYear_LabelVal")
        self.Name_LabelVal = QtWidgets.QLabel(self.centralwidget)
        self.Name_LabelVal.setGeometry(QtCore.QRect(250, 450, 55, 16))
        self.Name_LabelVal.setText("")
        self.Name_LabelVal.setObjectName("Name_LabelVal")
        self.NameLabel_Val = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel_Val.setGeometry(QtCore.QRect(550, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NameLabel_Val.setFont(font)
        self.NameLabel_Val.setObjectName("NameLabel_Val")
        self.CaptureBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CaptureBtn.setGeometry(QtCore.QRect(80, 430, 93, 28))
        self.CaptureBtn.setObjectName("CaptureBtn")
        self.UploadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.UploadBtn.setGeometry(QtCore.QRect(200, 430, 93, 28))
        self.UploadBtn.setObjectName("UploadBtn")
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel.setGeometry(QtCore.QRect(10, 540, 55, 16))
        self.StatusLabel.setObjectName("StatusLabel")
        self.StatusOfExecution = QtWidgets.QLabel(self.centralwidget)
        self.StatusOfExecution.setGeometry(QtCore.QRect(80, 540, 331, 16))
        self.StatusOfExecution.setText("")
        self.StatusOfExecution.setObjectName("StatusOfExecution")
        self.Branch_Label = QtWidgets.QLabel(self.centralwidget)
        self.Branch_Label.setGeometry(QtCore.QRect(390, 240, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Branch_Label.setFont(font)
        self.Branch_Label.setObjectName("Branch_Label")
        self.Branch_Val = QtWidgets.QLabel(self.centralwidget)
        self.Branch_Val.setGeometry(QtCore.QRect(560, 240, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Branch_Val.setFont(font)
        self.Branch_Val.setText("")
        self.Branch_Val.setObjectName("Branch_Val")
        self.Role_Label = QtWidgets.QLabel(self.centralwidget)
        self.Role_Label.setGeometry(QtCore.QRect(390, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Role_Label.setFont(font)
        self.Role_Label.setObjectName("Role_Label")
        self.Role_LabelVal = QtWidgets.QLabel(self.centralwidget)
        self.Role_LabelVal.setGeometry(QtCore.QRect(530, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Role_LabelVal.setFont(font)
        self.Role_LabelVal.setText("")
        self.Role_LabelVal.setObjectName("Role_LabelVal")
        self.CaptureBtn.clicked.connect(self.CaptureClicked)
        self.UploadBtn.clicked.connect(self.uploadPhotoAndDetect)
        self.Attendance_ConfirmButton.clicked.connect(self.MarkAttendance)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def CaptureClicked(self):
        self.StatusOfExecution.setText("Image Captured")
        self.logic = 2

    def MarkAttendance(self):
        db = dbClass.DbConnection()
        valuesFromDB = db.getnamefromrollno(int(self.RollNumer))
        array = [i for sub in valuesFromDB for i in sub]
        dictOfVal = {}
        dictOfVal['RollNumber'] = array[1]
        dictOfVal['FirstName'] = array[2]
        dictOfVal['LastName'] = array[2]
        now = datetime.datetime.now()
        dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
        dictOfVal['Date'] = dt_string
        dictOfVal['Status'] = 'Present'
        db.MarkAttendance(dictOfVal)
        self.StatusOfExecution.setText("Attendance Marked")

    # Starting Camera
    def onClicked(self):
        self.setvalues([])
        self.StatusOfExecution.setText("Initializing Camera....")
        cap = cv.VideoCapture(0)
        while(cap.isOpened()):
            ret,frame = cap.read()
            self.StatusOfExecution.setText("Camera Started....")
            self.Photo_Box.setText("")
            if ret == True:
                self.displayImage(frame, 1)
                cv.waitKey()
                if self.logic == 2:
                    self.value = self.value + 1
                    filePath = os.path.join(CapimageStorLoc,'1.jpg')
                    cv.imwrite(filePath,frame)
                    self.logic = 1
                    break
            else:
                print('return not found')
        cap.release()
        cv.destroyAllWindows()

    def uploadPhotoAndDetect(self):
        faceObj = face_recog()
        db = dbClass.DbConnection()
        self.StatusOfExecution.setText("Detecting Face.....")
        filePath = os.path.join(CapimageStorLoc, '1.jpg')
        filePathOfCroppedImage = faceObj.DetectFace(filePath)
        print("File path of cropped image ",str(filePathOfCroppedImage))
        if(filePathOfCroppedImage != None):
            self.Photo_Box.setPixmap(QtGui.QPixmap(filePathOfCroppedImage))
            rollNumber = faceObj.facePrediction(filePath)
            self.RollNumer = int(rollNumber)
            valuesFromDB = db.getnamefromrollno(int(rollNumber))
            self.setvalues([i for sub in valuesFromDB for i in sub])
            self.StatusOfExecution.setText("Face Detected")
        else:
            self.StatusOfExecution.setText("No face detected.....")

    def setvalues(self, arrayOfVal):

        if len(arrayOfVal) > 0:
            self.NameLabel_Val.setText(arrayOfVal[2] + " "+arrayOfVal[3])
            if (arrayOfVal[len(arrayOfVal) - 1] == "Student"):
                self.CurrentYear_LabelVal.show()
                self.CurrentYear_Label.show()
                currentYear = int(datetime.date.today().year) - int(arrayOfVal[4])
                self.CurrentYear_LabelVal.setText(str(currentYear))
            else:
                self.CurrentYear_LabelVal.hide()
                self.CurrentYear_Label.hide()
            self.Role_LabelVal.setText(arrayOfVal[len(arrayOfVal) - 1])
            self.RollNumber_LabelVal.setText(str(arrayOfVal[1]))
            self.Branch_Val.setText(arrayOfVal[5])
        else:
            self.NameLabel_Val.setText("")
            self.CurrentYear_LabelVal.setText("")
            self.RollNumber_LabelVal.setText("")
            self.Branch_Val.setText("")
            self.Role_LabelVal.setText("")

    # Displaying image of camera
    def displayImage(self, img, window=1):
        qformat = QImage.Format_Indexed8
        if(len(img.shape) == 3):
            if(img.shape[2] == 4):
                qformat=QImage.Format_RGBA8888
            else:
                qformat= QImage.Format_RGB888
        img = QImage(img,img.shape[1],img.shape[0],qformat)
        img = img.rgbSwapped()
        self.Photo_Box.setPixmap(QPixmap.fromImage(img))
        self.Photo_Box.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CameraButton.setText(_translate("MainWindow", "Start Camera"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.RollNumber_Label.setText(_translate("MainWindow", "ID"))
        self.CurrentYear_Label.setText(_translate("MainWindow", "Current year"))
        self.Attendance_ConfirmButton.setText(_translate("MainWindow", "Confirm Attendance"))
        self.CaptureBtn.setText(_translate("MainWindow", "Capture"))
        self.UploadBtn.setText(_translate("MainWindow", "Upload"))
        self.StatusLabel.setText(_translate("MainWindow", "Status :"))
        self.Branch_Label.setText(_translate("MainWindow", "Branch"))
        self.Role_Label.setText(_translate("MainWindow", "Role"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
